config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"
  resources :sessions, only: %i[new create destroy]
  get 'password' , to: 'passwords#new'
  post 'password' , to: 'passwords#create'
  get 'password/edit' , to: "passwords#edit"
  patch "password/edit" , to: "passwords#update"

  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  resources :orders, only: %i[index show create]

  resources :users do
    resources :addresses
  end

  resources :restaurants do
    resources :foods
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  # ASSOCIATIONS
  has_many :restaurants 
  has_many :addresses
  has_one :cart
  has_many :orders

  #VALIDATIONS
  validates :name, :email, :password, presence: true
  validates :password, confirmation: { case_sensitive: true }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :email, uniqueness: true
  validates :contact_number,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10 }
  
  def get_cart
    cart || create_cart
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @user = User.new
  end
 
  def create
    @user = User.new(user_params)
    if @user.save
      TaskLoggerJob.perform_later
      redirect_to new_session_path
    else 
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :contact_number, :password, :is_admin)
  end

end

app/views/users/_form.html.erb
<%= form_with model: @user, local: false  do |form| %>
  <div class="modal-body">
    <% if @user.errors.full_messages.any? %>
      <%= render "shared/error", object: @user %>
    <% end %>
    <%= form.label :name %><br>
    <div class="mb-3">
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <%= form.label :email %><br>
    <div class="mb-3">
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <%= form.label :contact %><br>
    <div class="mb-3">
      <%= form.text_field :contact_number, class: "form-control" %>
    </div>
    <%= form.label :password %><br>
    <div class="mb-3">
      <%= form.password_field :password, class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label "click here for signup as a admin" %>
      <%= form.check_box :is_admin %> <br>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary btn-lg close-modal" data-dismiss="modal">Close</button>
    <%= form.submit "signup",class: "btn btn-primary btn-lg" %>
  </div>
<% end %> 

app/views/users/index.html.erb
<div style="min-height:70vh">
  <div style="min-height:72vh">
    <% if current_user.present? %>
      <h1>Online Food Delivery</h1>
      <h1> 
        <% @restaurants.each do |restaurant| %>
          <div class="card" style="width: 20rem; display:inline-block;">
            <% if restaurant.image.present? %>
              <%= link_to restaurant_foods_path(restaurant.id) do %>
                <%= image_tag url_for(restaurant.image), class: "card-img-top", style: "width: 20rem" %>
              <% end %>       
            <% end %>
            <div class="card-block">
              <h4 class="card-title"><%= link_to restaurant.name, restaurant_foods_path(restaurant.id) %><br></h4>
              <h4 class="card-title"><%= restaurant.address %><br></h4>
              <% if restaurant.user == current_user %>
                <div class="d-flex justify-content-around align-items-center">
                  <%= link_to "Edit Restaurant", edit_restaurant_path(restaurant), class:"btn btn-primary btn-sm" %>
                  <%= button_to "delete", restaurant, method: "delete", class:"btn btn-primary btn-sm" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </h1>
    <% else %>
      <h1>
        Online Food Delivery<br>
        <%= link_to "Sign up", new_user_path, class: "btn btn-success", data: { bs_toggle: 'modal', bs_target: '#newUserModal', remote: true } %><br>
        <%= link_to "login", new_session_path, class: "btn btn-success" %>
      </h1>
    <%end%>
  </div>
</div>

<div class="modal fade" id="newUserModal" tabindex="-1" role="dialog" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">Create New User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="newUserForm">
      </div>
    </div>
  </div>
</div>

app/views/users/new.js.erb
$("#newUserForm").html("<%= escape_javascript render('form', user: @user) %>");
$(".close-modal").click();