config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"
  resources :sessions, only: %i[new create destroy]
  get 'password' , to: 'passwords#new'
  post 'password' , to: 'passwords#create'
  get 'password/edit' , to: "passwords#edit"
  patch "password/edit" , to: "passwords#update"

  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  resources :orders, only: %i[index show create]

  resources :users do
    resources :addresses
  end

  resources :restaurants do
    resources :foods
  end

end

app/views/shared/_error.html.erb
<div class="alert alert-danger">
  <% object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div>
  <div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">© 2022 Company, Inc</p>
    </footer>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-bg navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= render partial: "shared/sidebar" %>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if current_user.present? %>
          <% if current_user.is_admin? %>
            <li class="nav-item">
              <%= link_to "Restaurant", restaurants_path(current_user.id), class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Cart", cart_items_path(current_user.id), class: "nav-link" %>
            <span class="badge badge-info" id="count"><%= @current_cart.cart_items.count %></span>
          </li>
          <li class="nav-item">
            <%= link_to "Your Orders", orders_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Address", user_addresses_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "logout", {controller: "sessions", action: "destroy", id: "current_user.id" }, method: "delete", class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_path, class: "nav-link", data: { bs_toggle: 'modal', bs_target: '#newUserModal', remote: true } %><br>
          </li>
          <li class="nav-item">
            <%= link_to "login", new_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#">Profile</a>
  <a href="#">Services</a>
  <a href="#">Clients</a>
  <a href="#">Contact</a>
</div>
<span style="font-size:30px;cursor:pointer; color :white" onclick="openNav()">&#9776; </span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>