config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"
  resources :sessions, only: %i[new create destroy]
  get 'password' , to: 'passwords#new'
  post 'password' , to: 'passwords#create'
  get 'password/edit' , to: "passwords#edit"
  patch "password/edit" , to: "passwords#update"

  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  resources :orders, only: %i[index show create]

  resources :users do
    resources :addresses
  end

  resources :restaurants do
    resources :foods
  end

end

app/models/food.rb
class Food < ApplicationRecord

  # Associations
  belongs_to :restaurant
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_many_attached :images
  
  #VALIDATIONS
  validates :name, :price, :quantity, presence: true
  validates :images, presence: true

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :logged_in_user
  before_action :get_restaurant, only: %i[index new create edit update destroy]
  before_action :set_food, only: %i[edit update destroy]

  def index
    @foods = @restaurant.foods.all
  end

  def new
    @food = Food.new
  end
  
  def create
    @food = @restaurant.foods.new(food_params)
    if @food.save
      redirect_to restaurant_foods_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @food.update(food_params)
      redirect_to restaurant_foods_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food.destroy
    flash[:notice] = "Delete Successfully"
    redirect_to restaurant_foods_path, status: :see_other
  end

  private
  def food_params
    params.require(:food).permit(:name, :price, :quantity, images: [])
  end
  
  def get_restaurant
    @restaurant = Restaurant.find_by(id: params[:restaurant_id])
    if @restaurant.blank?
      flash[:errors] = "restaurant  does not exists"
      redirect_to restaurants_path
    end
  end

  def set_food
    @food = @restaurant.foods.find_by(id: params[:id])
    if @food.blank?
      flash[:errors] = "food  does not exists"
      redirect_to restaurant_foods_path
    end
  end
  
end

app/views/foods/_form.html.erb
<div style="min-height:72vh">
  <div class="w-25 container">
    <%= form_with model: [@restaurant, @food], local: true do |form| %>
      <% if @food.errors.full_messages.any? %>
        <%= render 'shared/error', object: @food %>
      <%end%>
      <%= form.label :name %><br>
      <div class="mb-3">
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <%= form.label :price %><br>
      <div class="mb-3">
        <%= form.text_field :price, class: "form-control" %>
      </div>
      <%= form.label :quantity %><br>
      <div class="mb-3">
        <%= form.text_field :quantity, class: "form-control" %>
      </div>
      <%= form.label :image %><br>
      <div class="mb-3">
        <%= form.file_field :images, multiple: true %>
      </div>
      <div>
      <%= form.submit @food.persisted? ? 'Edit' : 'Add' %>
      </div>
    <% end %>
  </div>
</div>

app/views/foods/edit.html.erb
<h1>Edit Dish</h1>
<%= render "form", food: @food %>

app/views/foods/index.html.erb
<div style="min-height:72vh">
  <h1>Dishes</h1>
  <% if @restaurant.user == current_user %>
    <h1><%= link_to "Add dish", new_restaurant_food_path, class: "btn btn-success" %></h1>
  <% end %>
  <h1> 
    <% @foods.each do |food| %>
      <div class="card" style="width: 20rem; display:inline-block;">
        <% if food.images.present? %>
          <% food.images.each do |img| %>
            <%= image_tag url_for(img), class: "card-img-top", style: "width: 20rem" %><br>
          <% end %>
        <% end %>
        <div class="card-block">
          <% if @restaurant.user == current_user %>
            <div class="d-flex justify-content-around align-items-center">
              <%= link_to "Edit Food", edit_restaurant_food_path(@restaurant,food), class:"btn btn-primary btn-sm" %>
              <%= button_to "delete", restaurant_food_path(@restaurant, food), method: "delete", class:"btn btn-primary btn-sm" %>
            </div>
            <h4 class="card-title"><%= food.name %><br></h4>
            <h4 class="card-title"><%= food.price %><br></h4>  
          <% else %>
            <h4 class="card-title"><%= food.name %><br></h4>
            <h4 class="card-title"><%= food.price %><br></h4>
          <% end %>
          <% if @current_cart.cart_items.pluck(:food_id).include?(food.id) %>
              <% @current_cart.cart_items.each do |cart_item| %>
                <%= link_to "Remove from cart", cart_item_path(cart_item), method: :delete, class:"btn btn-sm btn-primary" %>
                <% break %>
              <% end %>
          <% else %>
            <%= button_to "Add #{food.name} to cart", cart_items_path(:food_id => food.id), class:"btn btn-primary btn-sm" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </h1>
</div>

app/views/foods/new.html.erb
<h1>Create Dish</h1>
<%= render "form", food: @food %>