config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"
  resources :sessions, only: %i[new create destroy]
  get 'password' , to: 'passwords#new'
  post 'password' , to: 'passwords#create'
  get 'password/edit' , to: "passwords#edit"
  patch "password/edit" , to: "passwords#update"

  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  resources :orders, only: %i[index show create]

  resources :users do
    resources :addresses
  end

  resources :restaurants do
    resources :foods
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  # ASSOCIATIONS
  belongs_to :food
  belongs_to :cart

  def total_price
    self.food.price * quantity
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :get_cart_items, only: %i[destroy add_quantity reduce_quantity]

  def index
    @cart_items = @current_cart.cart_items.all
  end

  def create
    @food = Food.find_by(id: params[:food_id])
    @cart_item = @current_cart.cart_items.new(food_id: params[:food_id])
    @cart_item.save
    redirect_back(fallback_location: root_path)
  end 

  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js 
    end
  end  
  
  def add_quantity
    @cart_item.quantity += 1
    @cart_item.save
    respond_to do |format|
      format.js
    end
  end
  
  def reduce_quantity
    if @cart_item.quantity > 1
      @cart_item.quantity -= 1
    end
    @cart_item.save
    respond_to do |format|
      format.js
    end
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:quantity,:food_id, :cart_id)
  end

  def get_cart_items
    @cart_item = @current_cart.cart_items.find_by(id: params[:id])
  end

end

app/views/cart_items/add_quantity.js.erb
document.querySelector("#total").innerHTML = <%= @current_cart.total_cart_price  %>
document.querySelector("#total" + <%= @cart_item.id %>).innerHTML = <%= @cart_item.total_price  %>
document.querySelector("#quant" + <%= @cart_item.id %>).innerHTML = <%= @cart_item.quantity  %>

app/views/cart_items/destroy.js.erb
document.querySelector("#cartitem" + <%= @cart_item.id %>).remove();
document.querySelector("#total").innerHTML = <%= @current_cart.total_cart_price  %>
document.querySelector("#count").innerHTML = <%= @current_cart.cart_items.count %>

if (<%= @current_cart.cart_items.count <= 0 %>) {
$("#placeorder").hide();
}

app/views/cart_items/index.html.erb
<div style="min-height:72vh">
  <h1>Cart</h1>
    <div class="row">
      <% @current_cart.cart_items.each do |cart_item| %>
        <div class="col-md-4">
          <div class="card" id="cartitem<%= cart_item.id %>">
            <table class="table table-hover table-striped table-primary h5">
              <tbody>
              <tr>
                <td colspan = "2"><h1><%= cart_item.food.restaurant.name %></h1></td>
              </tr>
              <tr>
                <td>
                  Dish:-  
                </td>
                <td>
                  <%= cart_item.food.name %>
                </td>
              </tr>
              <tr>
                <td>
                  Price:-  
                </td>
                <td>
                  <%= number_to_currency(cart_item.food.price) %>
                </td>
              </tr>
              <tr>
                <td>
                  quantity:-  
                </td>
                <td>
                  <div id="quant<%= cart_item.id %>"><%= cart_item.quantity %></div>
                </td>
              </tr>
              <tr>
                <td>
                    Total Price:-  
                </td>
                <td>
                  <div id="total<%= cart_item.id %>"><%= number_to_currency(cart_item.total_price) %></div>
                </td>
              </tr>
            </table>
            <div class="d-flex justify-content-around align-items-center">
              <%= link_to("Add one", cart_item_add_path(:id => cart_item), method: :post, remote: true, class:"btn btn-sm btn-primary") %>
              <%= link_to "Reduce one", cart_item_reduce_path(:id => cart_item), method: :post, remote: true, class:"btn btn-sm btn-primary" %>
              <%= link_to("Remove item", cart_item_path(cart_item), method: :delete, remote: true, class:"btn btn-sm btn-primary") %>
            </div>     
          </div>
        </div>
      <% end %>
    </div>
    <h1>
      <% if @current_cart.cart_items.count > 0 %>
        <div class="mb-2" id='placeorder'>
          <div id="total"><%=  @current_cart.total_cart_price %></div>
          <%= form_with url: orders_path, method: :post do |form| %>
            <%= form.label :address %>
            <%= form.select :address, options_for_select(get_address)  %><br>
            <%= form.submit "Place Order", class:"btn btn-sm btn-primary" %>
          <% end %>
        </div>
      <% else %>
        Cart is Empty
      <% end %>
    </h1>
</div>

app/views/cart_items/reduce_quantity.js.erb
document.querySelector("#total").innerHTML = <%= @current_cart.total_cart_price  %>
document.querySelector("#total" + <%= @cart_item.id %>).innerHTML = <%= @cart_item.total_price  %>
document.querySelector("#quant" + <%= @cart_item.id %>).innerHTML = <%= @cart_item.quantity  %>